### ISSUE TITLE
system evolution empty

### ISSUE THREAD

**Issue by jdevoo** [smontanari/code-forensics#12]
Silvio, I ran `gulp system-evolution-analysis --dateFrom=2015-01-01 --dateTo=2017-12-31` against this repo `https://github.com/adrianco/spigo` which is a Go-based architecture simulation tool.

The task runs but the visualizations remain empty. I have not set up layerGroups but thought that was optional.

Any thoughts?

**Comment by smontanari** [comment]
The data is there (if you look into the generated report files the output folder). The problem is that you have specified (implicitly) only one data point and all you have is the aggregation of your metrics over that time interval, hence the diagrams don't really show anything meaningful. Being an _evolution_ analysis we want to instruct code-forensics to divide the time interval into a number of periods at the end of which metrics can be collected and data points can be created. In other words if you pass the timeSplit parameter (for instance "1m" for monthly periods) then you will start seeing data in your diagrams.
Such parameter is not strictly required to run the analysis, but I will document this edge case better in the wiki. Thanks for pointing it out
