### ISSUE TITLE
Question about system evolution

### ISSUE THREAD

**Issue by jdevoo** [smontanari/code-forensics#29]
Hello guys,
I ran a system evolution task against [RISE Lab Clipper](https://rise.cs.berkeley.edu/projects/clipper/) back in December and again Today using the following task and arguments

`system-evolution-analysis --dateFrom=2017-06-01 --dateTo=2018-03-01 --timeSplit=2w`

The two profiles vary as follows. I am wondering if the timeSplit needs to be adjusted for comparisons as the December peak no longer comes across in the Jun-Mar data set...

![sys_evol_dec](https://user-images.githubusercontent.com/16983/37336048-7922972a-26b0-11e8-91d7-3a6fd5eebe97.PNG)

![sys_evol_mar](https://user-images.githubusercontent.com/16983/37336058-7fffdfda-26b0-11e8-8824-1be712aa8030.PNG)

**Comment by smontanari** [comment]
I don't seem to see an issue comparing the two graphs. It looks to me as the December peak shows up in both, with a value somewhere between 5 and 10 revisions.  Also the second graph up until December resembles pretty closely the last third of the first graph, obviously not identical because the time scale is stretched.

**Comment by jdevoo** [comment]
duh! I got my intervals wrong! thank you!!
