### ISSUE TITLE
system evolution question

### ISSUE THREAD

**Issue by jdevoo** [smontanari/code-forensics#37]
Hello all,

I have been looking at system evolution for CrowdAI, a RoR-based machine learning competition site. I split the analysis as follows
```
	layerGroups: {
		'maint': [
			{ name: 'app', paths: ['app', 'db', 'config'] },
			{ name: 'test', paths: ['spec', 'scripts'] }
		]
	}
```
Somehow I obtain a short time series on 'test' but the cumulative revisions vary over the entire period. Same picture when I reduce the interval from 1m to 2w for the long period.

![system-evo-crowdai](https://user-images.githubusercontent.com/16983/47788902-5e3d6880-dd13-11e8-9c8b-aab107690453.PNG)

![system-evo-crowdai-rev](https://user-images.githubusercontent.com/16983/47789017-b1afb680-dd13-11e8-841c-b49b78dedfe8.PNG)

Not sure how to interpret this.

**Comment by smontanari** [comment]
I'll take a look

**Comment by jdevoo** [comment]
Sorry Silvio - yes; here's the gulpfile as well

```
// https://github.com/crowdAI/crowdai
require('code-forensics').configure({
	repository: {
		rootPath: 'repos/crowdai',
		excludePaths: [
			'log',
			'bin',
			'db',
			'doc',
			'docker',
			'vendor',
			'public',
			'lib',
			'config',
			'scripts',
			'**/+(.*|*.sql|*.svg|*.png|*.jpg|*.gif|*.ico|*.ini|*.ru|*.txt|*.csv|*.pdf|*.sh|*.example|*.lock|*.md|Procfile*|Gemfile|Rakefile|touchfile|tmpfile|*.json|*.scss)'
		]
	},
	layerGroups: {
		'maint': [
			{ name: 'app', paths: ['app'] },
			{ name: 'test', paths: ['spec'] }
		]
	},
	contributors: [
		['Sean Carrol', 'Sean Carroll', 'seanfcarrol', 'Sean', 'sean'],
		['SP Mohanty', 'spMohanty', 'S.P. Mohanty'], ['englhardt'],
		['Djilani Kebaili', 'bkDJ', 'DJ'], ['balakirevs'], ['Zgore14'],
		['ieggel'], ['XCaellaX'], ['Harry-Chen'], ['adrienpoly'],
		['farnir'], ['jonasrauber']
    ]
})
```

**Comment by smontanari** [comment]
I think I found out the glitch in the report. It's probably due to missing values in the generated reports, that would happen when there are no revisions for a certain period. In such case the value is undefined instead of 0, hence causing D3 to fail drawing the data plot. I labelled this issue as a bug and will do some more debugging.
In the meantime if you still want to see that particular layer trend (i.e. the *test* code) you could do it by temporarily changing your repo configuration to only have the `includePaths: ['spec']` and then running the system evolution report *without a layer group parameter*.
Thanks @jdevoo for reporting this. It's definitely an error, although happening in a rather exceptional case (no commits or revisions data)

**Comment by jdevoo** [comment]
Thanks Silvio for looking into it.
