### ISSUE TITLE
system evolution cumulative churn

### ISSUE THREAD

**Issue by jdevoo** [smontanari/code-forensics#45]
I ran code-forensics against a [repo ](https://github.com/jdevoo/twecoll/blob/master/twecoll) of mine with a single Python script. I developed this over a few years with minor work every now and then. The profile over the years is shown below.
Shouldn't cumulative churn keep increasing with the additions?

![image](https://user-images.githubusercontent.com/16983/67953582-b097ba80-fbef-11e9-885c-d6dc1ab189ad.png)

**Comment by smontanari** [comment]
it should, under the (fair) assumption that the net loc (added - deleted) is always positive. I'll take a look at your repo and see if there's anything wrong with the report

**Comment by smontanari** [comment]
Please ignore my previous comment (I'm going to delete it). You are 100% right, the cumulative lines represent the absolute number of lines changed (added or deleted) and it should always increase

**Comment by smontanari** [comment]
I've run the report and it seems fine to me. (I used a `timeSplit` value of `6m`)
![sea-ss](https://user-images.githubusercontent.com/293746/68097510-86a20900-ff0b-11e9-92a7-bd8cfac3074f.jpg)

**Comment by smontanari** [comment]
Moreover, while investigating the report logic, I discovered a potential issue caused by commit logs that don't carry file churn data (typically merge commits from other branches). In such case the system evolution report can present _holes_ because it fails to aggregate metrics correctly. This could or could not happen depending on the fragmentation of the log files (influenced by the `timeSplit` parameter).
I'll create quick patch to fix this behaviour

**Comment by smontanari** [comment]
I just released `2.3.1`. See if it helps with your report

**Comment by jdevoo** [comment]
thank you very much!!!
