### ISSUE TITLE
gulp list-analysis-tasks fails to start

### ISSUE THREAD

**Issue by mduerig** [smontanari/code-forensics#64]
```
$ gulp list-analysis-tasks
[16:43:03] Using gulpfile ~/Downloads/q/gulpfile.js
/usr/lib/nodejs/gulp/bin/gulp.js:132
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/lib/nodejs/gulp/bin/gulp.js:132:20
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by smontanari** [comment]
I'm not sure this issue is related to code-forensics. The stack trace shows a problem in a piece of code that is not in code-forensics. Plus, it seems to me you are running gulp from a different installation.
This problem seems more due to how you install code-forensics. Make sure you are running gulp version 4, moreover I would suggest you run gulp from the package that would come in the node_modules folder of the directory where you install code-forensics.

**Comment by mduerig** [comment]
Thanks @smontanari . Apparently I was not using the correct gulp version. Got it working now.
