### ISSUE TITLE
Git log empty and thus no plots generated

### ISSUE THREAD

**Issue by rbritto82** [smontanari/code-forensics#9]
Hi,

First, i would like to congratulate you for your work. Really nice job!

I tried to use the tool to analyze the hibernate-orm repository (https://github.com/hibernate/hibernate-orm.git). I tried the commands  "commit-message-analysis" and "hotspot-analysis". When I run the first command, nothing is generated, just empty files (log file and the json). When I try to run the second command, the following error occurs:

[09:48:00] Created: vcslog_2017-10-12_2017-10-12.log
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, open 'C:\Users\eriobro\Documents\Repositorie
s\hibernate-orm\hibernate-core\src\test\java\org\hibernate\test\type\TypeTest.ja
va'
    at Error (native)

 I'm running the tool in a Windows 7 machine. The used gulpfile is attached.

[gulpfile.txt](https://github.com/smontanari/code-forensics/files/1378478/gulpfile.txt)

Thanks a lot for your attention!

**Comment by smontanari** [comment]
Sorry for the delay but I was on holiday over the past two weeks.

- First: if you don't specify a start date code-forensics will only run for the current date and if no commits have been created for that day no reports will be created. 
- Secondly: running this tool on Windows has a high chance of failure, as the behaviour of nodejs on a Windows OS is different (and more complicated). I don't really support Windows (I state it in the README but probably not clearly enough) because I have no time to deal with all the aforementioned differences. 
I would strongly recommend that you install and run code-forensics in a linux box, or a VM, or even a docker container.
- Third: hibernate is written in java so any task that analyses complexity will not report anything because at the moment code-forensics only _understands_ JavaScript and Ruby (I need to make that clear as well in the README). However you can run many other tasks and still analyse the repository. Support for other languages can also be added but that needs time and possibly help.
- Finally: the gulpfile configuration example that I give in the README looks simple and only contains the location of the repository in the file system, but I would suggest you read the documentation and look into configuring many other parameters of code-forensics in order to target more effectively the type of analyses you intend to run

**Comment by rbritto82** [comment]
Hi, Silvio!

Thanks a lot for all the clarifications.

[ ]'s
Ricardo Britto
